dist: xenial
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
before_install:
  - sudo apt-get install -y lzop
install:
  - pip install -U tox-travis
  - sudo apt-get install lzop
script: tox
